error: Deprecate adbg_error_current
Because it was a little on the unsafe side (ABI wise, if fields change), and required to know the structure layout, it is deprecated.

But I added _line(), _function(), and _code() to retrieve last error parameters. Which I find a lot safer.